apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  namespace: default
  labels:
    app: frontend-deploy
spec:
  selector:
    matchLabels:
      app: frontend-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-deploy
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
        - name: frontend-deploy
          image: gopikondaji/backend:'30'
          resources:
            requests:
              cpu: 2400m
              memory: 2400Mi
            limits:
              cpu: 2400m
              memory: 2400Mi
          ports:
            - containerPort: 2424241
              name: frontend-deploy
      restartPolicy: Always
